language: node_js
node_js: lts/*
env:
  global:
  - secure: svyqm8/QtnkdPatP4Je3EWu0ojpDPxiAIlwddkhokj3R/FcLtL2Ls1xlLM8/uXtbqZQ6kx9z0vDCvsrN87C3nEobtyem3dj7ofy/f375dUoRIkpOTkorHKsJKmUquYK3orUFyBLwUMnSFTLgNdD3SjR/TrZbf8zORK3tO2g0zs5Pb2nQOrbb2NAVnkORnlTGEIve+sQtnBfsLcq4oW9pu2vfz6Zq/OS6sEulcwwdhaqmqLN3Q8W7dZ0Du1eGTdaw8MukZ5X6sZv+8LuSL0lhfN42PvaPvHjUiWNqLq+x8NNX2q8HAADnNPOAwTJVHhH5trKzy8HKwukkuji0ATsbxJd1TvP1y1nD4tTCT2Uqu25xu3lwSuv2DEe5CozE+V5J6isSitBNT4mKNqiEPufh5NZaTXLCmEZjHgPLnbUsrKwNjDuMtuswW0WC0dnWuCg/GHB5DHC6lnGduXJr0ePRoDANEMkTC8Mlf0gv3MZsFAIY0hYU915A6sh7vRwHDm2lAKXlhn07yy8M6YZYTC37EWv4rfBt//yu0Zv277hLa78OyBs/wx/u11PE4Vhfe5Lbs+OyZ6VmP/trdjqy4oyDl3uQo3OENQ7F/ysCvTbzb/AoLMdO6JgFPC4MsjPDJEBKM+Ca9CcuB60S6Q8e7AAsi1nitNbLwNBmFqiFhCRgeSU=
services:
- docker
script:
- npm run lint
- docker build -t danigatunes/unnamed .
deploy:
  on:
    branch: master
  provider: script
  script: echo ${DOCKER_PASSWORD} | docker login -u danigatunes --password-stdin && docker push danigatunes/unnamed  
  skip_cleanup: true
